# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/fighter/Downloads/clion-2018.1.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/fighter/Downloads/clion-2018.1.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fighter/wind_jvm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fighter/wind_jvm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/fighter/Downloads/clion-2018.1.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/fighter/Downloads/clion-2018.1.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fighter/wind_jvm/CMakeFiles /home/fighter/wind_jvm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fighter/wind_jvm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wind_vm

# Build rule for target.
wind_vm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wind_vm
.PHONY : wind_vm

# fast build rule for target.
wind_vm/fast:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/build
.PHONY : wind_vm/fast

src/ZipFile.o: src/ZipFile.cpp.o

.PHONY : src/ZipFile.o

# target to build an object file
src/ZipFile.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/ZipFile.cpp.o
.PHONY : src/ZipFile.cpp.o

src/ZipFile.i: src/ZipFile.cpp.i

.PHONY : src/ZipFile.i

# target to preprocess a source file
src/ZipFile.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/ZipFile.cpp.i
.PHONY : src/ZipFile.cpp.i

src/ZipFile.s: src/ZipFile.cpp.s

.PHONY : src/ZipFile.s

# target to generate assembly for a file
src/ZipFile.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/ZipFile.cpp.s
.PHONY : src/ZipFile.cpp.s

src/class_parser.o: src/class_parser.cpp.o

.PHONY : src/class_parser.o

# target to build an object file
src/class_parser.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/class_parser.cpp.o
.PHONY : src/class_parser.cpp.o

src/class_parser.i: src/class_parser.cpp.i

.PHONY : src/class_parser.i

# target to preprocess a source file
src/class_parser.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/class_parser.cpp.i
.PHONY : src/class_parser.cpp.i

src/class_parser.s: src/class_parser.cpp.s

.PHONY : src/class_parser.s

# target to generate assembly for a file
src/class_parser.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/class_parser.cpp.s
.PHONY : src/class_parser.cpp.s

src/classloader.o: src/classloader.cpp.o

.PHONY : src/classloader.o

# target to build an object file
src/classloader.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/classloader.cpp.o
.PHONY : src/classloader.cpp.o

src/classloader.i: src/classloader.cpp.i

.PHONY : src/classloader.i

# target to preprocess a source file
src/classloader.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/classloader.cpp.i
.PHONY : src/classloader.cpp.i

src/classloader.s: src/classloader.cpp.s

.PHONY : src/classloader.s

# target to generate assembly for a file
src/classloader.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/classloader.cpp.s
.PHONY : src/classloader.cpp.s

src/jarLister.o: src/jarLister.cpp.o

.PHONY : src/jarLister.o

# target to build an object file
src/jarLister.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/jarLister.cpp.o
.PHONY : src/jarLister.cpp.o

src/jarLister.i: src/jarLister.cpp.i

.PHONY : src/jarLister.i

# target to preprocess a source file
src/jarLister.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/jarLister.cpp.i
.PHONY : src/jarLister.cpp.i

src/jarLister.s: src/jarLister.cpp.s

.PHONY : src/jarLister.s

# target to generate assembly for a file
src/jarLister.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/jarLister.cpp.s
.PHONY : src/jarLister.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/native/java_io_FileDescriptor.o: src/native/java_io_FileDescriptor.cpp.o

.PHONY : src/native/java_io_FileDescriptor.o

# target to build an object file
src/native/java_io_FileDescriptor.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_io_FileDescriptor.cpp.o
.PHONY : src/native/java_io_FileDescriptor.cpp.o

src/native/java_io_FileDescriptor.i: src/native/java_io_FileDescriptor.cpp.i

.PHONY : src/native/java_io_FileDescriptor.i

# target to preprocess a source file
src/native/java_io_FileDescriptor.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_io_FileDescriptor.cpp.i
.PHONY : src/native/java_io_FileDescriptor.cpp.i

src/native/java_io_FileDescriptor.s: src/native/java_io_FileDescriptor.cpp.s

.PHONY : src/native/java_io_FileDescriptor.s

# target to generate assembly for a file
src/native/java_io_FileDescriptor.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_io_FileDescriptor.cpp.s
.PHONY : src/native/java_io_FileDescriptor.cpp.s

src/native/java_io_FileInputStream.o: src/native/java_io_FileInputStream.cpp.o

.PHONY : src/native/java_io_FileInputStream.o

# target to build an object file
src/native/java_io_FileInputStream.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_io_FileInputStream.cpp.o
.PHONY : src/native/java_io_FileInputStream.cpp.o

src/native/java_io_FileInputStream.i: src/native/java_io_FileInputStream.cpp.i

.PHONY : src/native/java_io_FileInputStream.i

# target to preprocess a source file
src/native/java_io_FileInputStream.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_io_FileInputStream.cpp.i
.PHONY : src/native/java_io_FileInputStream.cpp.i

src/native/java_io_FileInputStream.s: src/native/java_io_FileInputStream.cpp.s

.PHONY : src/native/java_io_FileInputStream.s

# target to generate assembly for a file
src/native/java_io_FileInputStream.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_io_FileInputStream.cpp.s
.PHONY : src/native/java_io_FileInputStream.cpp.s

src/native/java_io_FileOutputStream.o: src/native/java_io_FileOutputStream.cpp.o

.PHONY : src/native/java_io_FileOutputStream.o

# target to build an object file
src/native/java_io_FileOutputStream.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_io_FileOutputStream.cpp.o
.PHONY : src/native/java_io_FileOutputStream.cpp.o

src/native/java_io_FileOutputStream.i: src/native/java_io_FileOutputStream.cpp.i

.PHONY : src/native/java_io_FileOutputStream.i

# target to preprocess a source file
src/native/java_io_FileOutputStream.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_io_FileOutputStream.cpp.i
.PHONY : src/native/java_io_FileOutputStream.cpp.i

src/native/java_io_FileOutputStream.s: src/native/java_io_FileOutputStream.cpp.s

.PHONY : src/native/java_io_FileOutputStream.s

# target to generate assembly for a file
src/native/java_io_FileOutputStream.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_io_FileOutputStream.cpp.s
.PHONY : src/native/java_io_FileOutputStream.cpp.s

src/native/java_io_FileSystem.o: src/native/java_io_FileSystem.cpp.o

.PHONY : src/native/java_io_FileSystem.o

# target to build an object file
src/native/java_io_FileSystem.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_io_FileSystem.cpp.o
.PHONY : src/native/java_io_FileSystem.cpp.o

src/native/java_io_FileSystem.i: src/native/java_io_FileSystem.cpp.i

.PHONY : src/native/java_io_FileSystem.i

# target to preprocess a source file
src/native/java_io_FileSystem.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_io_FileSystem.cpp.i
.PHONY : src/native/java_io_FileSystem.cpp.i

src/native/java_io_FileSystem.s: src/native/java_io_FileSystem.cpp.s

.PHONY : src/native/java_io_FileSystem.s

# target to generate assembly for a file
src/native/java_io_FileSystem.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_io_FileSystem.cpp.s
.PHONY : src/native/java_io_FileSystem.cpp.s

src/native/java_io_UnixFileSystem.o: src/native/java_io_UnixFileSystem.cpp.o

.PHONY : src/native/java_io_UnixFileSystem.o

# target to build an object file
src/native/java_io_UnixFileSystem.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_io_UnixFileSystem.cpp.o
.PHONY : src/native/java_io_UnixFileSystem.cpp.o

src/native/java_io_UnixFileSystem.i: src/native/java_io_UnixFileSystem.cpp.i

.PHONY : src/native/java_io_UnixFileSystem.i

# target to preprocess a source file
src/native/java_io_UnixFileSystem.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_io_UnixFileSystem.cpp.i
.PHONY : src/native/java_io_UnixFileSystem.cpp.i

src/native/java_io_UnixFileSystem.s: src/native/java_io_UnixFileSystem.cpp.s

.PHONY : src/native/java_io_UnixFileSystem.s

# target to generate assembly for a file
src/native/java_io_UnixFileSystem.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_io_UnixFileSystem.cpp.s
.PHONY : src/native/java_io_UnixFileSystem.cpp.s

src/native/java_lang_Class.o: src/native/java_lang_Class.cpp.o

.PHONY : src/native/java_lang_Class.o

# target to build an object file
src/native/java_lang_Class.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Class.cpp.o
.PHONY : src/native/java_lang_Class.cpp.o

src/native/java_lang_Class.i: src/native/java_lang_Class.cpp.i

.PHONY : src/native/java_lang_Class.i

# target to preprocess a source file
src/native/java_lang_Class.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Class.cpp.i
.PHONY : src/native/java_lang_Class.cpp.i

src/native/java_lang_Class.s: src/native/java_lang_Class.cpp.s

.PHONY : src/native/java_lang_Class.s

# target to generate assembly for a file
src/native/java_lang_Class.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Class.cpp.s
.PHONY : src/native/java_lang_Class.cpp.s

src/native/java_lang_ClassLoader.o: src/native/java_lang_ClassLoader.cpp.o

.PHONY : src/native/java_lang_ClassLoader.o

# target to build an object file
src/native/java_lang_ClassLoader.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_ClassLoader.cpp.o
.PHONY : src/native/java_lang_ClassLoader.cpp.o

src/native/java_lang_ClassLoader.i: src/native/java_lang_ClassLoader.cpp.i

.PHONY : src/native/java_lang_ClassLoader.i

# target to preprocess a source file
src/native/java_lang_ClassLoader.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_ClassLoader.cpp.i
.PHONY : src/native/java_lang_ClassLoader.cpp.i

src/native/java_lang_ClassLoader.s: src/native/java_lang_ClassLoader.cpp.s

.PHONY : src/native/java_lang_ClassLoader.s

# target to generate assembly for a file
src/native/java_lang_ClassLoader.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_ClassLoader.cpp.s
.PHONY : src/native/java_lang_ClassLoader.cpp.s

src/native/java_lang_ClassLoader_nativeLibrary.o: src/native/java_lang_ClassLoader_nativeLibrary.cpp.o

.PHONY : src/native/java_lang_ClassLoader_nativeLibrary.o

# target to build an object file
src/native/java_lang_ClassLoader_nativeLibrary.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_ClassLoader_nativeLibrary.cpp.o
.PHONY : src/native/java_lang_ClassLoader_nativeLibrary.cpp.o

src/native/java_lang_ClassLoader_nativeLibrary.i: src/native/java_lang_ClassLoader_nativeLibrary.cpp.i

.PHONY : src/native/java_lang_ClassLoader_nativeLibrary.i

# target to preprocess a source file
src/native/java_lang_ClassLoader_nativeLibrary.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_ClassLoader_nativeLibrary.cpp.i
.PHONY : src/native/java_lang_ClassLoader_nativeLibrary.cpp.i

src/native/java_lang_ClassLoader_nativeLibrary.s: src/native/java_lang_ClassLoader_nativeLibrary.cpp.s

.PHONY : src/native/java_lang_ClassLoader_nativeLibrary.s

# target to generate assembly for a file
src/native/java_lang_ClassLoader_nativeLibrary.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_ClassLoader_nativeLibrary.cpp.s
.PHONY : src/native/java_lang_ClassLoader_nativeLibrary.cpp.s

src/native/java_lang_Double.o: src/native/java_lang_Double.cpp.o

.PHONY : src/native/java_lang_Double.o

# target to build an object file
src/native/java_lang_Double.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Double.cpp.o
.PHONY : src/native/java_lang_Double.cpp.o

src/native/java_lang_Double.i: src/native/java_lang_Double.cpp.i

.PHONY : src/native/java_lang_Double.i

# target to preprocess a source file
src/native/java_lang_Double.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Double.cpp.i
.PHONY : src/native/java_lang_Double.cpp.i

src/native/java_lang_Double.s: src/native/java_lang_Double.cpp.s

.PHONY : src/native/java_lang_Double.s

# target to generate assembly for a file
src/native/java_lang_Double.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Double.cpp.s
.PHONY : src/native/java_lang_Double.cpp.s

src/native/java_lang_Float.o: src/native/java_lang_Float.cpp.o

.PHONY : src/native/java_lang_Float.o

# target to build an object file
src/native/java_lang_Float.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Float.cpp.o
.PHONY : src/native/java_lang_Float.cpp.o

src/native/java_lang_Float.i: src/native/java_lang_Float.cpp.i

.PHONY : src/native/java_lang_Float.i

# target to preprocess a source file
src/native/java_lang_Float.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Float.cpp.i
.PHONY : src/native/java_lang_Float.cpp.i

src/native/java_lang_Float.s: src/native/java_lang_Float.cpp.s

.PHONY : src/native/java_lang_Float.s

# target to generate assembly for a file
src/native/java_lang_Float.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Float.cpp.s
.PHONY : src/native/java_lang_Float.cpp.s

src/native/java_lang_Object.o: src/native/java_lang_Object.cpp.o

.PHONY : src/native/java_lang_Object.o

# target to build an object file
src/native/java_lang_Object.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Object.cpp.o
.PHONY : src/native/java_lang_Object.cpp.o

src/native/java_lang_Object.i: src/native/java_lang_Object.cpp.i

.PHONY : src/native/java_lang_Object.i

# target to preprocess a source file
src/native/java_lang_Object.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Object.cpp.i
.PHONY : src/native/java_lang_Object.cpp.i

src/native/java_lang_Object.s: src/native/java_lang_Object.cpp.s

.PHONY : src/native/java_lang_Object.s

# target to generate assembly for a file
src/native/java_lang_Object.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Object.cpp.s
.PHONY : src/native/java_lang_Object.cpp.s

src/native/java_lang_Package.o: src/native/java_lang_Package.cpp.o

.PHONY : src/native/java_lang_Package.o

# target to build an object file
src/native/java_lang_Package.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Package.cpp.o
.PHONY : src/native/java_lang_Package.cpp.o

src/native/java_lang_Package.i: src/native/java_lang_Package.cpp.i

.PHONY : src/native/java_lang_Package.i

# target to preprocess a source file
src/native/java_lang_Package.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Package.cpp.i
.PHONY : src/native/java_lang_Package.cpp.i

src/native/java_lang_Package.s: src/native/java_lang_Package.cpp.s

.PHONY : src/native/java_lang_Package.s

# target to generate assembly for a file
src/native/java_lang_Package.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Package.cpp.s
.PHONY : src/native/java_lang_Package.cpp.s

src/native/java_lang_Runtime.o: src/native/java_lang_Runtime.cpp.o

.PHONY : src/native/java_lang_Runtime.o

# target to build an object file
src/native/java_lang_Runtime.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Runtime.cpp.o
.PHONY : src/native/java_lang_Runtime.cpp.o

src/native/java_lang_Runtime.i: src/native/java_lang_Runtime.cpp.i

.PHONY : src/native/java_lang_Runtime.i

# target to preprocess a source file
src/native/java_lang_Runtime.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Runtime.cpp.i
.PHONY : src/native/java_lang_Runtime.cpp.i

src/native/java_lang_Runtime.s: src/native/java_lang_Runtime.cpp.s

.PHONY : src/native/java_lang_Runtime.s

# target to generate assembly for a file
src/native/java_lang_Runtime.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Runtime.cpp.s
.PHONY : src/native/java_lang_Runtime.cpp.s

src/native/java_lang_Shutdown.o: src/native/java_lang_Shutdown.cpp.o

.PHONY : src/native/java_lang_Shutdown.o

# target to build an object file
src/native/java_lang_Shutdown.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Shutdown.cpp.o
.PHONY : src/native/java_lang_Shutdown.cpp.o

src/native/java_lang_Shutdown.i: src/native/java_lang_Shutdown.cpp.i

.PHONY : src/native/java_lang_Shutdown.i

# target to preprocess a source file
src/native/java_lang_Shutdown.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Shutdown.cpp.i
.PHONY : src/native/java_lang_Shutdown.cpp.i

src/native/java_lang_Shutdown.s: src/native/java_lang_Shutdown.cpp.s

.PHONY : src/native/java_lang_Shutdown.s

# target to generate assembly for a file
src/native/java_lang_Shutdown.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Shutdown.cpp.s
.PHONY : src/native/java_lang_Shutdown.cpp.s

src/native/java_lang_String.o: src/native/java_lang_String.cpp.o

.PHONY : src/native/java_lang_String.o

# target to build an object file
src/native/java_lang_String.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_String.cpp.o
.PHONY : src/native/java_lang_String.cpp.o

src/native/java_lang_String.i: src/native/java_lang_String.cpp.i

.PHONY : src/native/java_lang_String.i

# target to preprocess a source file
src/native/java_lang_String.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_String.cpp.i
.PHONY : src/native/java_lang_String.cpp.i

src/native/java_lang_String.s: src/native/java_lang_String.cpp.s

.PHONY : src/native/java_lang_String.s

# target to generate assembly for a file
src/native/java_lang_String.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_String.cpp.s
.PHONY : src/native/java_lang_String.cpp.s

src/native/java_lang_System.o: src/native/java_lang_System.cpp.o

.PHONY : src/native/java_lang_System.o

# target to build an object file
src/native/java_lang_System.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_System.cpp.o
.PHONY : src/native/java_lang_System.cpp.o

src/native/java_lang_System.i: src/native/java_lang_System.cpp.i

.PHONY : src/native/java_lang_System.i

# target to preprocess a source file
src/native/java_lang_System.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_System.cpp.i
.PHONY : src/native/java_lang_System.cpp.i

src/native/java_lang_System.s: src/native/java_lang_System.cpp.s

.PHONY : src/native/java_lang_System.s

# target to generate assembly for a file
src/native/java_lang_System.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_System.cpp.s
.PHONY : src/native/java_lang_System.cpp.s

src/native/java_lang_Thread.o: src/native/java_lang_Thread.cpp.o

.PHONY : src/native/java_lang_Thread.o

# target to build an object file
src/native/java_lang_Thread.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Thread.cpp.o
.PHONY : src/native/java_lang_Thread.cpp.o

src/native/java_lang_Thread.i: src/native/java_lang_Thread.cpp.i

.PHONY : src/native/java_lang_Thread.i

# target to preprocess a source file
src/native/java_lang_Thread.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Thread.cpp.i
.PHONY : src/native/java_lang_Thread.cpp.i

src/native/java_lang_Thread.s: src/native/java_lang_Thread.cpp.s

.PHONY : src/native/java_lang_Thread.s

# target to generate assembly for a file
src/native/java_lang_Thread.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Thread.cpp.s
.PHONY : src/native/java_lang_Thread.cpp.s

src/native/java_lang_Throwable.o: src/native/java_lang_Throwable.cpp.o

.PHONY : src/native/java_lang_Throwable.o

# target to build an object file
src/native/java_lang_Throwable.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Throwable.cpp.o
.PHONY : src/native/java_lang_Throwable.cpp.o

src/native/java_lang_Throwable.i: src/native/java_lang_Throwable.cpp.i

.PHONY : src/native/java_lang_Throwable.i

# target to preprocess a source file
src/native/java_lang_Throwable.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Throwable.cpp.i
.PHONY : src/native/java_lang_Throwable.cpp.i

src/native/java_lang_Throwable.s: src/native/java_lang_Throwable.cpp.s

.PHONY : src/native/java_lang_Throwable.s

# target to generate assembly for a file
src/native/java_lang_Throwable.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_Throwable.cpp.s
.PHONY : src/native/java_lang_Throwable.cpp.s

src/native/java_lang_invoke_MethodHandle.o: src/native/java_lang_invoke_MethodHandle.cpp.o

.PHONY : src/native/java_lang_invoke_MethodHandle.o

# target to build an object file
src/native/java_lang_invoke_MethodHandle.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_invoke_MethodHandle.cpp.o
.PHONY : src/native/java_lang_invoke_MethodHandle.cpp.o

src/native/java_lang_invoke_MethodHandle.i: src/native/java_lang_invoke_MethodHandle.cpp.i

.PHONY : src/native/java_lang_invoke_MethodHandle.i

# target to preprocess a source file
src/native/java_lang_invoke_MethodHandle.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_invoke_MethodHandle.cpp.i
.PHONY : src/native/java_lang_invoke_MethodHandle.cpp.i

src/native/java_lang_invoke_MethodHandle.s: src/native/java_lang_invoke_MethodHandle.cpp.s

.PHONY : src/native/java_lang_invoke_MethodHandle.s

# target to generate assembly for a file
src/native/java_lang_invoke_MethodHandle.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_invoke_MethodHandle.cpp.s
.PHONY : src/native/java_lang_invoke_MethodHandle.cpp.s

src/native/java_lang_invoke_MethodHandleNatives.o: src/native/java_lang_invoke_MethodHandleNatives.cpp.o

.PHONY : src/native/java_lang_invoke_MethodHandleNatives.o

# target to build an object file
src/native/java_lang_invoke_MethodHandleNatives.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_invoke_MethodHandleNatives.cpp.o
.PHONY : src/native/java_lang_invoke_MethodHandleNatives.cpp.o

src/native/java_lang_invoke_MethodHandleNatives.i: src/native/java_lang_invoke_MethodHandleNatives.cpp.i

.PHONY : src/native/java_lang_invoke_MethodHandleNatives.i

# target to preprocess a source file
src/native/java_lang_invoke_MethodHandleNatives.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_invoke_MethodHandleNatives.cpp.i
.PHONY : src/native/java_lang_invoke_MethodHandleNatives.cpp.i

src/native/java_lang_invoke_MethodHandleNatives.s: src/native/java_lang_invoke_MethodHandleNatives.cpp.s

.PHONY : src/native/java_lang_invoke_MethodHandleNatives.s

# target to generate assembly for a file
src/native/java_lang_invoke_MethodHandleNatives.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_invoke_MethodHandleNatives.cpp.s
.PHONY : src/native/java_lang_invoke_MethodHandleNatives.cpp.s

src/native/java_lang_reflect_Array.o: src/native/java_lang_reflect_Array.cpp.o

.PHONY : src/native/java_lang_reflect_Array.o

# target to build an object file
src/native/java_lang_reflect_Array.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_reflect_Array.cpp.o
.PHONY : src/native/java_lang_reflect_Array.cpp.o

src/native/java_lang_reflect_Array.i: src/native/java_lang_reflect_Array.cpp.i

.PHONY : src/native/java_lang_reflect_Array.i

# target to preprocess a source file
src/native/java_lang_reflect_Array.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_reflect_Array.cpp.i
.PHONY : src/native/java_lang_reflect_Array.cpp.i

src/native/java_lang_reflect_Array.s: src/native/java_lang_reflect_Array.cpp.s

.PHONY : src/native/java_lang_reflect_Array.s

# target to generate assembly for a file
src/native/java_lang_reflect_Array.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_lang_reflect_Array.cpp.s
.PHONY : src/native/java_lang_reflect_Array.cpp.s

src/native/java_security_AccessController.o: src/native/java_security_AccessController.cpp.o

.PHONY : src/native/java_security_AccessController.o

# target to build an object file
src/native/java_security_AccessController.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_security_AccessController.cpp.o
.PHONY : src/native/java_security_AccessController.cpp.o

src/native/java_security_AccessController.i: src/native/java_security_AccessController.cpp.i

.PHONY : src/native/java_security_AccessController.i

# target to preprocess a source file
src/native/java_security_AccessController.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_security_AccessController.cpp.i
.PHONY : src/native/java_security_AccessController.cpp.i

src/native/java_security_AccessController.s: src/native/java_security_AccessController.cpp.s

.PHONY : src/native/java_security_AccessController.s

# target to generate assembly for a file
src/native/java_security_AccessController.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_security_AccessController.cpp.s
.PHONY : src/native/java_security_AccessController.cpp.s

src/native/java_util_concurrent_atomic_AtomicLong.o: src/native/java_util_concurrent_atomic_AtomicLong.cpp.o

.PHONY : src/native/java_util_concurrent_atomic_AtomicLong.o

# target to build an object file
src/native/java_util_concurrent_atomic_AtomicLong.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_util_concurrent_atomic_AtomicLong.cpp.o
.PHONY : src/native/java_util_concurrent_atomic_AtomicLong.cpp.o

src/native/java_util_concurrent_atomic_AtomicLong.i: src/native/java_util_concurrent_atomic_AtomicLong.cpp.i

.PHONY : src/native/java_util_concurrent_atomic_AtomicLong.i

# target to preprocess a source file
src/native/java_util_concurrent_atomic_AtomicLong.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_util_concurrent_atomic_AtomicLong.cpp.i
.PHONY : src/native/java_util_concurrent_atomic_AtomicLong.cpp.i

src/native/java_util_concurrent_atomic_AtomicLong.s: src/native/java_util_concurrent_atomic_AtomicLong.cpp.s

.PHONY : src/native/java_util_concurrent_atomic_AtomicLong.s

# target to generate assembly for a file
src/native/java_util_concurrent_atomic_AtomicLong.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/java_util_concurrent_atomic_AtomicLong.cpp.s
.PHONY : src/native/java_util_concurrent_atomic_AtomicLong.cpp.s

src/native/native.o: src/native/native.cpp.o

.PHONY : src/native/native.o

# target to build an object file
src/native/native.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/native.cpp.o
.PHONY : src/native/native.cpp.o

src/native/native.i: src/native/native.cpp.i

.PHONY : src/native/native.i

# target to preprocess a source file
src/native/native.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/native.cpp.i
.PHONY : src/native/native.cpp.i

src/native/native.s: src/native/native.cpp.s

.PHONY : src/native/native.s

# target to generate assembly for a file
src/native/native.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/native.cpp.s
.PHONY : src/native/native.cpp.s

src/native/sun_misc_URLClassPath.o: src/native/sun_misc_URLClassPath.cpp.o

.PHONY : src/native/sun_misc_URLClassPath.o

# target to build an object file
src/native/sun_misc_URLClassPath.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_misc_URLClassPath.cpp.o
.PHONY : src/native/sun_misc_URLClassPath.cpp.o

src/native/sun_misc_URLClassPath.i: src/native/sun_misc_URLClassPath.cpp.i

.PHONY : src/native/sun_misc_URLClassPath.i

# target to preprocess a source file
src/native/sun_misc_URLClassPath.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_misc_URLClassPath.cpp.i
.PHONY : src/native/sun_misc_URLClassPath.cpp.i

src/native/sun_misc_URLClassPath.s: src/native/sun_misc_URLClassPath.cpp.s

.PHONY : src/native/sun_misc_URLClassPath.s

# target to generate assembly for a file
src/native/sun_misc_URLClassPath.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_misc_URLClassPath.cpp.s
.PHONY : src/native/sun_misc_URLClassPath.cpp.s

src/native/sun_misc_Unsafe.o: src/native/sun_misc_Unsafe.cpp.o

.PHONY : src/native/sun_misc_Unsafe.o

# target to build an object file
src/native/sun_misc_Unsafe.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_misc_Unsafe.cpp.o
.PHONY : src/native/sun_misc_Unsafe.cpp.o

src/native/sun_misc_Unsafe.i: src/native/sun_misc_Unsafe.cpp.i

.PHONY : src/native/sun_misc_Unsafe.i

# target to preprocess a source file
src/native/sun_misc_Unsafe.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_misc_Unsafe.cpp.i
.PHONY : src/native/sun_misc_Unsafe.cpp.i

src/native/sun_misc_Unsafe.s: src/native/sun_misc_Unsafe.cpp.s

.PHONY : src/native/sun_misc_Unsafe.s

# target to generate assembly for a file
src/native/sun_misc_Unsafe.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_misc_Unsafe.cpp.s
.PHONY : src/native/sun_misc_Unsafe.cpp.s

src/native/sun_misc_VM.o: src/native/sun_misc_VM.cpp.o

.PHONY : src/native/sun_misc_VM.o

# target to build an object file
src/native/sun_misc_VM.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_misc_VM.cpp.o
.PHONY : src/native/sun_misc_VM.cpp.o

src/native/sun_misc_VM.i: src/native/sun_misc_VM.cpp.i

.PHONY : src/native/sun_misc_VM.i

# target to preprocess a source file
src/native/sun_misc_VM.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_misc_VM.cpp.i
.PHONY : src/native/sun_misc_VM.cpp.i

src/native/sun_misc_VM.s: src/native/sun_misc_VM.cpp.s

.PHONY : src/native/sun_misc_VM.s

# target to generate assembly for a file
src/native/sun_misc_VM.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_misc_VM.cpp.s
.PHONY : src/native/sun_misc_VM.cpp.s

src/native/sun_misc_signal.o: src/native/sun_misc_signal.cpp.o

.PHONY : src/native/sun_misc_signal.o

# target to build an object file
src/native/sun_misc_signal.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_misc_signal.cpp.o
.PHONY : src/native/sun_misc_signal.cpp.o

src/native/sun_misc_signal.i: src/native/sun_misc_signal.cpp.i

.PHONY : src/native/sun_misc_signal.i

# target to preprocess a source file
src/native/sun_misc_signal.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_misc_signal.cpp.i
.PHONY : src/native/sun_misc_signal.cpp.i

src/native/sun_misc_signal.s: src/native/sun_misc_signal.cpp.s

.PHONY : src/native/sun_misc_signal.s

# target to generate assembly for a file
src/native/sun_misc_signal.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_misc_signal.cpp.s
.PHONY : src/native/sun_misc_signal.cpp.s

src/native/sun_reflect_NativeConstructorAccessorImpl.o: src/native/sun_reflect_NativeConstructorAccessorImpl.cpp.o

.PHONY : src/native/sun_reflect_NativeConstructorAccessorImpl.o

# target to build an object file
src/native/sun_reflect_NativeConstructorAccessorImpl.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_reflect_NativeConstructorAccessorImpl.cpp.o
.PHONY : src/native/sun_reflect_NativeConstructorAccessorImpl.cpp.o

src/native/sun_reflect_NativeConstructorAccessorImpl.i: src/native/sun_reflect_NativeConstructorAccessorImpl.cpp.i

.PHONY : src/native/sun_reflect_NativeConstructorAccessorImpl.i

# target to preprocess a source file
src/native/sun_reflect_NativeConstructorAccessorImpl.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_reflect_NativeConstructorAccessorImpl.cpp.i
.PHONY : src/native/sun_reflect_NativeConstructorAccessorImpl.cpp.i

src/native/sun_reflect_NativeConstructorAccessorImpl.s: src/native/sun_reflect_NativeConstructorAccessorImpl.cpp.s

.PHONY : src/native/sun_reflect_NativeConstructorAccessorImpl.s

# target to generate assembly for a file
src/native/sun_reflect_NativeConstructorAccessorImpl.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_reflect_NativeConstructorAccessorImpl.cpp.s
.PHONY : src/native/sun_reflect_NativeConstructorAccessorImpl.cpp.s

src/native/sun_reflect_NativeMethodAccessorImpl.o: src/native/sun_reflect_NativeMethodAccessorImpl.cpp.o

.PHONY : src/native/sun_reflect_NativeMethodAccessorImpl.o

# target to build an object file
src/native/sun_reflect_NativeMethodAccessorImpl.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_reflect_NativeMethodAccessorImpl.cpp.o
.PHONY : src/native/sun_reflect_NativeMethodAccessorImpl.cpp.o

src/native/sun_reflect_NativeMethodAccessorImpl.i: src/native/sun_reflect_NativeMethodAccessorImpl.cpp.i

.PHONY : src/native/sun_reflect_NativeMethodAccessorImpl.i

# target to preprocess a source file
src/native/sun_reflect_NativeMethodAccessorImpl.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_reflect_NativeMethodAccessorImpl.cpp.i
.PHONY : src/native/sun_reflect_NativeMethodAccessorImpl.cpp.i

src/native/sun_reflect_NativeMethodAccessorImpl.s: src/native/sun_reflect_NativeMethodAccessorImpl.cpp.s

.PHONY : src/native/sun_reflect_NativeMethodAccessorImpl.s

# target to generate assembly for a file
src/native/sun_reflect_NativeMethodAccessorImpl.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_reflect_NativeMethodAccessorImpl.cpp.s
.PHONY : src/native/sun_reflect_NativeMethodAccessorImpl.cpp.s

src/native/sun_reflect_Reflection.o: src/native/sun_reflect_Reflection.cpp.o

.PHONY : src/native/sun_reflect_Reflection.o

# target to build an object file
src/native/sun_reflect_Reflection.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_reflect_Reflection.cpp.o
.PHONY : src/native/sun_reflect_Reflection.cpp.o

src/native/sun_reflect_Reflection.i: src/native/sun_reflect_Reflection.cpp.i

.PHONY : src/native/sun_reflect_Reflection.i

# target to preprocess a source file
src/native/sun_reflect_Reflection.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_reflect_Reflection.cpp.i
.PHONY : src/native/sun_reflect_Reflection.cpp.i

src/native/sun_reflect_Reflection.s: src/native/sun_reflect_Reflection.cpp.s

.PHONY : src/native/sun_reflect_Reflection.s

# target to generate assembly for a file
src/native/sun_reflect_Reflection.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/native/sun_reflect_Reflection.cpp.s
.PHONY : src/native/sun_reflect_Reflection.cpp.s

src/runtime/annotation.o: src/runtime/annotation.cpp.o

.PHONY : src/runtime/annotation.o

# target to build an object file
src/runtime/annotation.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/annotation.cpp.o
.PHONY : src/runtime/annotation.cpp.o

src/runtime/annotation.i: src/runtime/annotation.cpp.i

.PHONY : src/runtime/annotation.i

# target to preprocess a source file
src/runtime/annotation.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/annotation.cpp.i
.PHONY : src/runtime/annotation.cpp.i

src/runtime/annotation.s: src/runtime/annotation.cpp.s

.PHONY : src/runtime/annotation.s

# target to generate assembly for a file
src/runtime/annotation.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/annotation.cpp.s
.PHONY : src/runtime/annotation.cpp.s

src/runtime/bytecodeEngine.o: src/runtime/bytecodeEngine.cpp.o

.PHONY : src/runtime/bytecodeEngine.o

# target to build an object file
src/runtime/bytecodeEngine.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/bytecodeEngine.cpp.o
.PHONY : src/runtime/bytecodeEngine.cpp.o

src/runtime/bytecodeEngine.i: src/runtime/bytecodeEngine.cpp.i

.PHONY : src/runtime/bytecodeEngine.i

# target to preprocess a source file
src/runtime/bytecodeEngine.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/bytecodeEngine.cpp.i
.PHONY : src/runtime/bytecodeEngine.cpp.i

src/runtime/bytecodeEngine.s: src/runtime/bytecodeEngine.cpp.s

.PHONY : src/runtime/bytecodeEngine.s

# target to generate assembly for a file
src/runtime/bytecodeEngine.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/bytecodeEngine.cpp.s
.PHONY : src/runtime/bytecodeEngine.cpp.s

src/runtime/constantpool.o: src/runtime/constantpool.cpp.o

.PHONY : src/runtime/constantpool.o

# target to build an object file
src/runtime/constantpool.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/constantpool.cpp.o
.PHONY : src/runtime/constantpool.cpp.o

src/runtime/constantpool.i: src/runtime/constantpool.cpp.i

.PHONY : src/runtime/constantpool.i

# target to preprocess a source file
src/runtime/constantpool.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/constantpool.cpp.i
.PHONY : src/runtime/constantpool.cpp.i

src/runtime/constantpool.s: src/runtime/constantpool.cpp.s

.PHONY : src/runtime/constantpool.s

# target to generate assembly for a file
src/runtime/constantpool.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/constantpool.cpp.s
.PHONY : src/runtime/constantpool.cpp.s

src/runtime/field.o: src/runtime/field.cpp.o

.PHONY : src/runtime/field.o

# target to build an object file
src/runtime/field.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/field.cpp.o
.PHONY : src/runtime/field.cpp.o

src/runtime/field.i: src/runtime/field.cpp.i

.PHONY : src/runtime/field.i

# target to preprocess a source file
src/runtime/field.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/field.cpp.i
.PHONY : src/runtime/field.cpp.i

src/runtime/field.s: src/runtime/field.cpp.s

.PHONY : src/runtime/field.s

# target to generate assembly for a file
src/runtime/field.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/field.cpp.s
.PHONY : src/runtime/field.cpp.s

src/runtime/gc.o: src/runtime/gc.cpp.o

.PHONY : src/runtime/gc.o

# target to build an object file
src/runtime/gc.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/gc.cpp.o
.PHONY : src/runtime/gc.cpp.o

src/runtime/gc.i: src/runtime/gc.cpp.i

.PHONY : src/runtime/gc.i

# target to preprocess a source file
src/runtime/gc.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/gc.cpp.i
.PHONY : src/runtime/gc.cpp.i

src/runtime/gc.s: src/runtime/gc.cpp.s

.PHONY : src/runtime/gc.s

# target to generate assembly for a file
src/runtime/gc.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/gc.cpp.s
.PHONY : src/runtime/gc.cpp.s

src/runtime/klass.o: src/runtime/klass.cpp.o

.PHONY : src/runtime/klass.o

# target to build an object file
src/runtime/klass.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/klass.cpp.o
.PHONY : src/runtime/klass.cpp.o

src/runtime/klass.i: src/runtime/klass.cpp.i

.PHONY : src/runtime/klass.i

# target to preprocess a source file
src/runtime/klass.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/klass.cpp.i
.PHONY : src/runtime/klass.cpp.i

src/runtime/klass.s: src/runtime/klass.cpp.s

.PHONY : src/runtime/klass.s

# target to generate assembly for a file
src/runtime/klass.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/klass.cpp.s
.PHONY : src/runtime/klass.cpp.s

src/runtime/method.o: src/runtime/method.cpp.o

.PHONY : src/runtime/method.o

# target to build an object file
src/runtime/method.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/method.cpp.o
.PHONY : src/runtime/method.cpp.o

src/runtime/method.i: src/runtime/method.cpp.i

.PHONY : src/runtime/method.i

# target to preprocess a source file
src/runtime/method.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/method.cpp.i
.PHONY : src/runtime/method.cpp.i

src/runtime/method.s: src/runtime/method.cpp.s

.PHONY : src/runtime/method.s

# target to generate assembly for a file
src/runtime/method.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/method.cpp.s
.PHONY : src/runtime/method.cpp.s

src/runtime/oop.o: src/runtime/oop.cpp.o

.PHONY : src/runtime/oop.o

# target to build an object file
src/runtime/oop.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/oop.cpp.o
.PHONY : src/runtime/oop.cpp.o

src/runtime/oop.i: src/runtime/oop.cpp.i

.PHONY : src/runtime/oop.i

# target to preprocess a source file
src/runtime/oop.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/oop.cpp.i
.PHONY : src/runtime/oop.cpp.i

src/runtime/oop.s: src/runtime/oop.cpp.s

.PHONY : src/runtime/oop.s

# target to generate assembly for a file
src/runtime/oop.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/oop.cpp.s
.PHONY : src/runtime/oop.cpp.s

src/runtime/openJdkNative.o: src/runtime/openJdkNative.cpp.o

.PHONY : src/runtime/openJdkNative.o

# target to build an object file
src/runtime/openJdkNative.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/openJdkNative.cpp.o
.PHONY : src/runtime/openJdkNative.cpp.o

src/runtime/openJdkNative.i: src/runtime/openJdkNative.cpp.i

.PHONY : src/runtime/openJdkNative.i

# target to preprocess a source file
src/runtime/openJdkNative.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/openJdkNative.cpp.i
.PHONY : src/runtime/openJdkNative.cpp.i

src/runtime/openJdkNative.s: src/runtime/openJdkNative.cpp.s

.PHONY : src/runtime/openJdkNative.s

# target to generate assembly for a file
src/runtime/openJdkNative.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/openJdkNative.cpp.s
.PHONY : src/runtime/openJdkNative.cpp.s

src/runtime/thread.o: src/runtime/thread.cpp.o

.PHONY : src/runtime/thread.o

# target to build an object file
src/runtime/thread.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/thread.cpp.o
.PHONY : src/runtime/thread.cpp.o

src/runtime/thread.i: src/runtime/thread.cpp.i

.PHONY : src/runtime/thread.i

# target to preprocess a source file
src/runtime/thread.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/thread.cpp.i
.PHONY : src/runtime/thread.cpp.i

src/runtime/thread.s: src/runtime/thread.cpp.s

.PHONY : src/runtime/thread.s

# target to generate assembly for a file
src/runtime/thread.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/runtime/thread.cpp.s
.PHONY : src/runtime/thread.cpp.s

src/system_directory.o: src/system_directory.cpp.o

.PHONY : src/system_directory.o

# target to build an object file
src/system_directory.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/system_directory.cpp.o
.PHONY : src/system_directory.cpp.o

src/system_directory.i: src/system_directory.cpp.i

.PHONY : src/system_directory.i

# target to preprocess a source file
src/system_directory.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/system_directory.cpp.i
.PHONY : src/system_directory.cpp.i

src/system_directory.s: src/system_directory.cpp.s

.PHONY : src/system_directory.s

# target to generate assembly for a file
src/system_directory.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/system_directory.cpp.s
.PHONY : src/system_directory.cpp.s

src/utils/lock.o: src/utils/lock.cpp.o

.PHONY : src/utils/lock.o

# target to build an object file
src/utils/lock.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/utils/lock.cpp.o
.PHONY : src/utils/lock.cpp.o

src/utils/lock.i: src/utils/lock.cpp.i

.PHONY : src/utils/lock.i

# target to preprocess a source file
src/utils/lock.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/utils/lock.cpp.i
.PHONY : src/utils/lock.cpp.i

src/utils/lock.s: src/utils/lock.cpp.s

.PHONY : src/utils/lock.s

# target to generate assembly for a file
src/utils/lock.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/utils/lock.cpp.s
.PHONY : src/utils/lock.cpp.s

src/utils/os.o: src/utils/os.cpp.o

.PHONY : src/utils/os.o

# target to build an object file
src/utils/os.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/utils/os.cpp.o
.PHONY : src/utils/os.cpp.o

src/utils/os.i: src/utils/os.cpp.i

.PHONY : src/utils/os.i

# target to preprocess a source file
src/utils/os.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/utils/os.cpp.i
.PHONY : src/utils/os.cpp.i

src/utils/os.s: src/utils/os.cpp.s

.PHONY : src/utils/os.s

# target to generate assembly for a file
src/utils/os.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/utils/os.cpp.s
.PHONY : src/utils/os.cpp.s

src/utils/synchronize_wcout.o: src/utils/synchronize_wcout.cpp.o

.PHONY : src/utils/synchronize_wcout.o

# target to build an object file
src/utils/synchronize_wcout.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/utils/synchronize_wcout.cpp.o
.PHONY : src/utils/synchronize_wcout.cpp.o

src/utils/synchronize_wcout.i: src/utils/synchronize_wcout.cpp.i

.PHONY : src/utils/synchronize_wcout.i

# target to preprocess a source file
src/utils/synchronize_wcout.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/utils/synchronize_wcout.cpp.i
.PHONY : src/utils/synchronize_wcout.cpp.i

src/utils/synchronize_wcout.s: src/utils/synchronize_wcout.cpp.s

.PHONY : src/utils/synchronize_wcout.s

# target to generate assembly for a file
src/utils/synchronize_wcout.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/utils/synchronize_wcout.cpp.s
.PHONY : src/utils/synchronize_wcout.cpp.s

src/utils/utils.o: src/utils/utils.cpp.o

.PHONY : src/utils/utils.o

# target to build an object file
src/utils/utils.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/utils/utils.cpp.o
.PHONY : src/utils/utils.cpp.o

src/utils/utils.i: src/utils/utils.cpp.i

.PHONY : src/utils/utils.i

# target to preprocess a source file
src/utils/utils.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/utils/utils.cpp.i
.PHONY : src/utils/utils.cpp.i

src/utils/utils.s: src/utils/utils.cpp.s

.PHONY : src/utils/utils.s

# target to generate assembly for a file
src/utils/utils.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/utils/utils.cpp.s
.PHONY : src/utils/utils.cpp.s

src/wind_jvm.o: src/wind_jvm.cpp.o

.PHONY : src/wind_jvm.o

# target to build an object file
src/wind_jvm.cpp.o:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/wind_jvm.cpp.o
.PHONY : src/wind_jvm.cpp.o

src/wind_jvm.i: src/wind_jvm.cpp.i

.PHONY : src/wind_jvm.i

# target to preprocess a source file
src/wind_jvm.cpp.i:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/wind_jvm.cpp.i
.PHONY : src/wind_jvm.cpp.i

src/wind_jvm.s: src/wind_jvm.cpp.s

.PHONY : src/wind_jvm.s

# target to generate assembly for a file
src/wind_jvm.cpp.s:
	$(MAKE) -f CMakeFiles/wind_vm.dir/build.make CMakeFiles/wind_vm.dir/src/wind_jvm.cpp.s
.PHONY : src/wind_jvm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... wind_vm"
	@echo "... src/ZipFile.o"
	@echo "... src/ZipFile.i"
	@echo "... src/ZipFile.s"
	@echo "... src/class_parser.o"
	@echo "... src/class_parser.i"
	@echo "... src/class_parser.s"
	@echo "... src/classloader.o"
	@echo "... src/classloader.i"
	@echo "... src/classloader.s"
	@echo "... src/jarLister.o"
	@echo "... src/jarLister.i"
	@echo "... src/jarLister.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/native/java_io_FileDescriptor.o"
	@echo "... src/native/java_io_FileDescriptor.i"
	@echo "... src/native/java_io_FileDescriptor.s"
	@echo "... src/native/java_io_FileInputStream.o"
	@echo "... src/native/java_io_FileInputStream.i"
	@echo "... src/native/java_io_FileInputStream.s"
	@echo "... src/native/java_io_FileOutputStream.o"
	@echo "... src/native/java_io_FileOutputStream.i"
	@echo "... src/native/java_io_FileOutputStream.s"
	@echo "... src/native/java_io_FileSystem.o"
	@echo "... src/native/java_io_FileSystem.i"
	@echo "... src/native/java_io_FileSystem.s"
	@echo "... src/native/java_io_UnixFileSystem.o"
	@echo "... src/native/java_io_UnixFileSystem.i"
	@echo "... src/native/java_io_UnixFileSystem.s"
	@echo "... src/native/java_lang_Class.o"
	@echo "... src/native/java_lang_Class.i"
	@echo "... src/native/java_lang_Class.s"
	@echo "... src/native/java_lang_ClassLoader.o"
	@echo "... src/native/java_lang_ClassLoader.i"
	@echo "... src/native/java_lang_ClassLoader.s"
	@echo "... src/native/java_lang_ClassLoader_nativeLibrary.o"
	@echo "... src/native/java_lang_ClassLoader_nativeLibrary.i"
	@echo "... src/native/java_lang_ClassLoader_nativeLibrary.s"
	@echo "... src/native/java_lang_Double.o"
	@echo "... src/native/java_lang_Double.i"
	@echo "... src/native/java_lang_Double.s"
	@echo "... src/native/java_lang_Float.o"
	@echo "... src/native/java_lang_Float.i"
	@echo "... src/native/java_lang_Float.s"
	@echo "... src/native/java_lang_Object.o"
	@echo "... src/native/java_lang_Object.i"
	@echo "... src/native/java_lang_Object.s"
	@echo "... src/native/java_lang_Package.o"
	@echo "... src/native/java_lang_Package.i"
	@echo "... src/native/java_lang_Package.s"
	@echo "... src/native/java_lang_Runtime.o"
	@echo "... src/native/java_lang_Runtime.i"
	@echo "... src/native/java_lang_Runtime.s"
	@echo "... src/native/java_lang_Shutdown.o"
	@echo "... src/native/java_lang_Shutdown.i"
	@echo "... src/native/java_lang_Shutdown.s"
	@echo "... src/native/java_lang_String.o"
	@echo "... src/native/java_lang_String.i"
	@echo "... src/native/java_lang_String.s"
	@echo "... src/native/java_lang_System.o"
	@echo "... src/native/java_lang_System.i"
	@echo "... src/native/java_lang_System.s"
	@echo "... src/native/java_lang_Thread.o"
	@echo "... src/native/java_lang_Thread.i"
	@echo "... src/native/java_lang_Thread.s"
	@echo "... src/native/java_lang_Throwable.o"
	@echo "... src/native/java_lang_Throwable.i"
	@echo "... src/native/java_lang_Throwable.s"
	@echo "... src/native/java_lang_invoke_MethodHandle.o"
	@echo "... src/native/java_lang_invoke_MethodHandle.i"
	@echo "... src/native/java_lang_invoke_MethodHandle.s"
	@echo "... src/native/java_lang_invoke_MethodHandleNatives.o"
	@echo "... src/native/java_lang_invoke_MethodHandleNatives.i"
	@echo "... src/native/java_lang_invoke_MethodHandleNatives.s"
	@echo "... src/native/java_lang_reflect_Array.o"
	@echo "... src/native/java_lang_reflect_Array.i"
	@echo "... src/native/java_lang_reflect_Array.s"
	@echo "... src/native/java_security_AccessController.o"
	@echo "... src/native/java_security_AccessController.i"
	@echo "... src/native/java_security_AccessController.s"
	@echo "... src/native/java_util_concurrent_atomic_AtomicLong.o"
	@echo "... src/native/java_util_concurrent_atomic_AtomicLong.i"
	@echo "... src/native/java_util_concurrent_atomic_AtomicLong.s"
	@echo "... src/native/native.o"
	@echo "... src/native/native.i"
	@echo "... src/native/native.s"
	@echo "... src/native/sun_misc_URLClassPath.o"
	@echo "... src/native/sun_misc_URLClassPath.i"
	@echo "... src/native/sun_misc_URLClassPath.s"
	@echo "... src/native/sun_misc_Unsafe.o"
	@echo "... src/native/sun_misc_Unsafe.i"
	@echo "... src/native/sun_misc_Unsafe.s"
	@echo "... src/native/sun_misc_VM.o"
	@echo "... src/native/sun_misc_VM.i"
	@echo "... src/native/sun_misc_VM.s"
	@echo "... src/native/sun_misc_signal.o"
	@echo "... src/native/sun_misc_signal.i"
	@echo "... src/native/sun_misc_signal.s"
	@echo "... src/native/sun_reflect_NativeConstructorAccessorImpl.o"
	@echo "... src/native/sun_reflect_NativeConstructorAccessorImpl.i"
	@echo "... src/native/sun_reflect_NativeConstructorAccessorImpl.s"
	@echo "... src/native/sun_reflect_NativeMethodAccessorImpl.o"
	@echo "... src/native/sun_reflect_NativeMethodAccessorImpl.i"
	@echo "... src/native/sun_reflect_NativeMethodAccessorImpl.s"
	@echo "... src/native/sun_reflect_Reflection.o"
	@echo "... src/native/sun_reflect_Reflection.i"
	@echo "... src/native/sun_reflect_Reflection.s"
	@echo "... src/runtime/annotation.o"
	@echo "... src/runtime/annotation.i"
	@echo "... src/runtime/annotation.s"
	@echo "... src/runtime/bytecodeEngine.o"
	@echo "... src/runtime/bytecodeEngine.i"
	@echo "... src/runtime/bytecodeEngine.s"
	@echo "... src/runtime/constantpool.o"
	@echo "... src/runtime/constantpool.i"
	@echo "... src/runtime/constantpool.s"
	@echo "... src/runtime/field.o"
	@echo "... src/runtime/field.i"
	@echo "... src/runtime/field.s"
	@echo "... src/runtime/gc.o"
	@echo "... src/runtime/gc.i"
	@echo "... src/runtime/gc.s"
	@echo "... src/runtime/klass.o"
	@echo "... src/runtime/klass.i"
	@echo "... src/runtime/klass.s"
	@echo "... src/runtime/method.o"
	@echo "... src/runtime/method.i"
	@echo "... src/runtime/method.s"
	@echo "... src/runtime/oop.o"
	@echo "... src/runtime/oop.i"
	@echo "... src/runtime/oop.s"
	@echo "... src/runtime/openJdkNative.o"
	@echo "... src/runtime/openJdkNative.i"
	@echo "... src/runtime/openJdkNative.s"
	@echo "... src/runtime/thread.o"
	@echo "... src/runtime/thread.i"
	@echo "... src/runtime/thread.s"
	@echo "... src/system_directory.o"
	@echo "... src/system_directory.i"
	@echo "... src/system_directory.s"
	@echo "... src/utils/lock.o"
	@echo "... src/utils/lock.i"
	@echo "... src/utils/lock.s"
	@echo "... src/utils/os.o"
	@echo "... src/utils/os.i"
	@echo "... src/utils/os.s"
	@echo "... src/utils/synchronize_wcout.o"
	@echo "... src/utils/synchronize_wcout.i"
	@echo "... src/utils/synchronize_wcout.s"
	@echo "... src/utils/utils.o"
	@echo "... src/utils/utils.i"
	@echo "... src/utils/utils.s"
	@echo "... src/wind_jvm.o"
	@echo "... src/wind_jvm.i"
	@echo "... src/wind_jvm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

