/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test19 */

#ifndef _Included_Test19
#define _Included_Test19
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test19
 * Method:    concat
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Test19_concat
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
